/**
 * Categorias de serviço alinhadas com a home (ServicosSection).
 * Usado em: ServicoCategoriaPage, NovaEmpresaPage, listagens de empresa.
 */
export const CATEGORIAS_SERVICO: Record<string, string> = {
  // Beleza
  salao: "Salão de Beleza",
  barbeiro: "Barbeiro",
  manicure: "Manicure",
  estetica: "Estética",
  maquiagem: "Maquiagem",
  sobrancelha: "Sobrancelha",
  depilacao: "Depilação",
  cosmeticos: "Cosméticos",
  // Serviços
  reparos: "Reparos",
  eletricista: "Eletricista",
  encanador: "Encanador",
  obras: "Obras",
  limpeza: "Limpeza",
  dedetizacao: "Dedetização",
  chaveiro: "Chaveiro",
  pintor: "Pintor",
  marceneiro: "Marceneiro",
  serralheria: "Serralheria",
  vidraceiro: "Vidraceiro",
  "ar-condicionado": "Ar Condicionado",
  jardinagem: "Jardinagem",
  mudancas: "Mudanças",
  diarista: "Diarista",
  costura: "Costura",
  // Profissionais
  advogado: "Advogado",
  contador: "Contador",
  despachante: "Despachante",
  engenheiro: "Engenheiro",
  arquiteto: "Arquiteto",
  corretor: "Corretor",
  fotografo: "Fotógrafo",
  aulas: "Aulas Particulares",
  idiomas: "Idiomas",
  informatica: "Informática",
  eventos: "Eventos",
  // Saúde
  clinica: "Clínica",
  dentista: "Dentista",
  psicologo: "Psicólogo",
  fisioterapeuta: "Fisioterapeuta",
  nutricionista: "Nutricionista",
  personal: "Personal Trainer",
  academia: "Academia",
  massagista: "Massagista",
  farmacia: "Farmácia",
  // Comércio
  desapega: "Marketplace local",
  lojas: "Lojas",
  promocoes: "Promoções",
  restaurantes: "Restaurantes",
  entregador: "Delivery",
  moda: "Moda",
  eletronicos: "Eletrônicos",
  // Veículos
  mecanico: "Mecânico",
  "lava-jato": "Lava Jato",
  "auto-pecas": "Auto Peças",
  guincho: "Guincho",
  funilaria: "Funilaria",
  borracharia: "Borracharia",
  vistoria: "Vistoria",
  motorista: "Motorista",
  // Pets
  veterinario: "Veterinário",
  pet: "Banho e Tosa",
  petshop: "Pet Shop",
  adestrador: "Adestrador",
  "hotel-pet": "Hotel Pet",
  passeador: "Passeador",
  // Outros
  influenciadores: "Influenciadores",
  outros: "Outros",
};

/** Nome + ícone (emoji) para exibição em headers/cards */
export const CATEGORIAS_SERVICO_META: Record<string, { nome: string; icone: string }> = {
  salao: { nome: "Salão de Beleza", icone: "💇" },
  barbeiro: { nome: "Barbeiro", icone: "💈" },
  manicure: { nome: "Manicure", icone: "💅" },
  estetica: { nome: "Estética", icone: "✨" },
  maquiagem: { nome: "Maquiagem", icone: "💄" },
  sobrancelha: { nome: "Sobrancelha", icone: "🪮" },
  depilacao: { nome: "Depilação", icone: "🌸" },
  cosmeticos: { nome: "Cosméticos", icone: "💄" },
  reparos: { nome: "Reparos", icone: "🔧" },
  eletricista: { nome: "Eletricista", icone: "⚡" },
  encanador: { nome: "Encanador", icone: "🚿" },
  obras: { nome: "Obras", icone: "🏗️" },
  limpeza: { nome: "Limpeza", icone: "✨" },
  dedetizacao: { nome: "Dedetização", icone: "🪲" },
  chaveiro: { nome: "Chaveiro", icone: "🔑" },
  pintor: { nome: "Pintor", icone: "🎨" },
  marceneiro: { nome: "Marceneiro", icone: "🪑" },
  serralheria: { nome: "Serralheria", icone: "⚙️" },
  vidraceiro: { nome: "Vidraceiro", icone: "🪟" },
  "ar-condicionado": { nome: "Ar Condicionado", icone: "❄️" },
  jardinagem: { nome: "Jardinagem", icone: "🌳" },
  mudancas: { nome: "Mudanças", icone: "🚚" },
  diarista: { nome: "Diarista", icone: "🏠" },
  costura: { nome: "Costura", icone: "🧵" },
  advogado: { nome: "Advogado", icone: "⚖️" },
  contador: { nome: "Contador", icone: "📊" },
  despachante: { nome: "Despachante", icone: "📄" },
  engenheiro: { nome: "Engenheiro", icone: "🏗️" },
  arquiteto: { nome: "Arquiteto", icone: "📐" },
  corretor: { nome: "Corretor", icone: "🏡" },
  fotografo: { nome: "Fotógrafo", icone: "📷" },
  aulas: { nome: "Aulas Particulares", icone: "📚" },
  idiomas: { nome: "Idiomas", icone: "🌎" },
  informatica: { nome: "Informática", icone: "💻" },
  eventos: { nome: "Eventos", icone: "🎉" },
  clinica: { nome: "Clínica", icone: "🏥" },
  dentista: { nome: "Dentista", icone: "🦷" },
  psicologo: { nome: "Psicólogo", icone: "🧠" },
  fisioterapeuta: { nome: "Fisioterapeuta", icone: "🦴" },
  nutricionista: { nome: "Nutricionista", icone: "🍎" },
  personal: { nome: "Personal Trainer", icone: "🏋️" },
  academia: { nome: "Academia", icone: "💪" },
  massagista: { nome: "Massagista", icone: "💆" },
  farmacia: { nome: "Farmácia", icone: "💊" },
  desapega: { nome: "Marketplace local", icone: "🛍️" },
  lojas: { nome: "Lojas", icone: "🏪" },
  promocoes: { nome: "Promoções", icone: "🏷️" },
  restaurantes: { nome: "Restaurantes", icone: "🍽️" },
  entregador: { nome: "Delivery", icone: "🚴" },
  moda: { nome: "Moda", icone: "👗" },
  eletronicos: { nome: "Eletrônicos", icone: "📱" },
  mecanico: { nome: "Mecânico", icone: "🔧" },
  "lava-jato": { nome: "Lava Jato", icone: "🚿" },
  "auto-pecas": { nome: "Auto Peças", icone: "⚙️" },
  guincho: { nome: "Guincho", icone: "🚗" },
  funilaria: { nome: "Funilaria", icone: "🔨" },
  borracharia: { nome: "Borracharia", icone: "🔄" },
  vistoria: { nome: "Vistoria", icone: "📋" },
  motorista: { nome: "Motorista", icone: "🚙" },
  veterinario: { nome: "Veterinário", icone: "🩺" },
  pet: { nome: "Banho e Tosa", icone: "🐕" },
  petshop: { nome: "Pet Shop", icone: "🐾" },
  adestrador: { nome: "Adestrador", icone: "🦮" },
  "hotel-pet": { nome: "Hotel Pet", icone: "🏨" },
  passeador: { nome: "Passeador", icone: "🦮" },
  influenciadores: { nome: "Influenciadores", icone: "📱" },
  outros: { nome: "Outros", icone: "📦" },
};
