export type IconifyServicoItem = {
  value: string;
  label: string;
  group: string;
};

export const ICONIFY_SERVICO_LIBRARY: IconifyServicoItem[] = [
  { value: "mdi:storefront-outline", label: "Loja", group: "Comercio" },
  { value: "mdi:shopping-outline", label: "Compras", group: "Comercio" },
  { value: "mdi:shopping-search-outline", label: "Pesquisa de produto", group: "Comercio" },
  { value: "mdi:tag-outline", label: "Promocao", group: "Comercio" },
  { value: "mdi:cash-register", label: "Caixa", group: "Comercio" },
  { value: "mdi:cart-outline", label: "Carrinho", group: "Comercio" },
  { value: "mdi:package-variant-closed", label: "Pacote", group: "Comercio" },
  { value: "mdi:barcode-scan", label: "Codigo de barras", group: "Comercio" },
  { value: "mdi:food-outline", label: "Comida", group: "Alimentacao" },
  { value: "mdi:silverware-fork-knife", label: "Restaurante", group: "Alimentacao" },
  { value: "mdi:glass-mug-variant", label: "Bar", group: "Alimentacao" },
  { value: "mdi:coffee-outline", label: "Cafe", group: "Alimentacao" },
  { value: "mdi:pizza", label: "Pizza", group: "Alimentacao" },
  { value: "mdi:food-croissant", label: "Padaria", group: "Alimentacao" },
  { value: "mdi:food-apple-outline", label: "Mercearia", group: "Alimentacao" },
  { value: "mdi:truck-delivery-outline", label: "Delivery", group: "Alimentacao" },
  { value: "mdi:face-man-shimmer-outline", label: "Barbeiro", group: "Beleza" },
  { value: "mdi:hair-dryer-outline", label: "Salao", group: "Beleza" },
  { value: "mdi:hand-front-left-outline", label: "Manicure", group: "Beleza" },
  { value: "mdi:spa-outline", label: "Estetica", group: "Beleza" },
  { value: "mdi:lipstick", label: "Maquiagem", group: "Beleza" },
  { value: "mdi:mirror-rectangle", label: "Studio", group: "Beleza" },
  { value: "mdi:broom", label: "Limpeza", group: "Casa" },
  { value: "mdi:hammer-wrench", label: "Reparos", group: "Casa" },
  { value: "mdi:lightning-bolt-outline", label: "Eletricista", group: "Casa" },
  { value: "mdi:pipe-wrench", label: "Encanador", group: "Casa" },
  { value: "mdi:key-outline", label: "Chaveiro", group: "Casa" },
  { value: "mdi:home-roof", label: "Casa", group: "Casa" },
  { value: "mdi:home-search-outline", label: "Imovel", group: "Casa" },
  { value: "mdi:window-open-variant", label: "Vidracaria", group: "Casa" },
  { value: "mdi:paint-outline", label: "Pintor", group: "Casa" },
  { value: "mdi:sofa-outline", label: "Marcenaria", group: "Casa" },
  { value: "mdi:flower-outline", label: "Jardinagem", group: "Casa" },
  { value: "mdi:cart-variant", label: "Mudanca", group: "Casa" },
  { value: "mdi:dump-truck", label: "Obras", group: "Casa" },
  { value: "mdi:hard-hat", label: "Construcao", group: "Casa" },
  { value: "mdi:car-outline", label: "Carro", group: "Veiculos" },
  { value: "mdi:car-wrench", label: "Mecanico", group: "Veiculos" },
  { value: "mdi:car-brake-alert", label: "Funilaria", group: "Veiculos" },
  { value: "mdi:car-tire-alert", label: "Borracharia", group: "Veiculos" },
  { value: "mdi:car-wash", label: "Lava jato", group: "Veiculos" },
  { value: "mdi:tow-truck", label: "Guincho", group: "Veiculos" },
  { value: "mdi:motorbike", label: "Moto", group: "Veiculos" },
  { value: "mdi:steering", label: "Motorista", group: "Veiculos" },
  { value: "mdi:ambulance", label: "Saude", group: "Saude" },
  { value: "mdi:hospital-box-outline", label: "Clinica", group: "Saude" },
  { value: "mdi:tooth-outline", label: "Dentista", group: "Saude" },
  { value: "mdi:brain", label: "Psicologo", group: "Saude" },
  { value: "mdi:meditation", label: "Terapia", group: "Saude" },
  { value: "mdi:heart-pulse", label: "Cardio", group: "Saude" },
  { value: "mdi:pill", label: "Farmacia", group: "Saude" },
  { value: "mdi:dumbbell", label: "Academia", group: "Saude" },
  { value: "mdi:food-apple", label: "Nutricao", group: "Saude" },
  { value: "mdi:human-male-board", label: "Personal", group: "Saude" },
  { value: "mdi:bone", label: "Fisioterapia", group: "Saude" },
  { value: "mdi:gavel", label: "Advogado", group: "Profissionais" },
  { value: "mdi:calculator-variant-outline", label: "Contador", group: "Profissionais" },
  { value: "mdi:file-document-edit-outline", label: "Despachante", group: "Profissionais" },
  { value: "mdi:briefcase-account-outline", label: "Consultor", group: "Profissionais" },
  { value: "mdi:account-tie-outline", label: "Executivo", group: "Profissionais" },
  { value: "mdi:school-outline", label: "Aulas", group: "Profissionais" },
  { value: "mdi:translate", label: "Idiomas", group: "Profissionais" },
  { value: "mdi:laptop", label: "Informatica", group: "Profissionais" },
  { value: "mdi:camera-outline", label: "Fotografo", group: "Profissionais" },
  { value: "mdi:account-voice", label: "Locutor", group: "Profissionais" },
  { value: "mdi:microphone-outline", label: "Musica", group: "Profissionais" },
  { value: "mdi:calendar-star", label: "Eventos", group: "Profissionais" },
  { value: "mdi:office-building-outline", label: "Escritorio", group: "Profissionais" },
  { value: "mdi:dog-side", label: "Pet", group: "Pets" },
  { value: "mdi:paw-outline", label: "Pet shop", group: "Pets" },
  { value: "mdi:dog-service", label: "Adestrador", group: "Pets" },
  { value: "mdi:home-heart", label: "Hotel pet", group: "Pets" },
  { value: "mdi:dog", label: "Passeador", group: "Pets" },
  { value: "mdi:stethoscope", label: "Veterinario", group: "Pets" },
  { value: "mdi:rabbit", label: "Animais", group: "Pets" },
  { value: "mdi:store-marker-outline", label: "Mercado local", group: "Comercio" },
  { value: "mdi:ticket-percent-outline", label: "Cupom", group: "Comercio" },
  { value: "mdi:cellphone", label: "Eletronicos", group: "Comercio" },
  { value: "mdi:tshirt-crew-outline", label: "Moda", group: "Comercio" },
  { value: "mdi:gift-outline", label: "Presentes", group: "Comercio" },
  { value: "tabler:tools", label: "Ferramentas", group: "Utilitarios" },
  { value: "tabler:tool", label: "Servico tecnico", group: "Utilitarios" },
  { value: "tabler:building-store", label: "Comercio local", group: "Utilitarios" },
  { value: "tabler:building-community", label: "Comunidade", group: "Utilitarios" },
  { value: "tabler:home-hand", label: "Assistencia", group: "Utilitarios" },
  { value: "tabler:home-plus", label: "Novo servico", group: "Utilitarios" },
  { value: "tabler:home-cog", label: "Manutencao", group: "Utilitarios" },
  { value: "tabler:needle-thread", label: "Costura", group: "Utilitarios" },
  { value: "tabler:bolt", label: "Energia", group: "Utilitarios" },
  { value: "tabler:road", label: "Transporte", group: "Utilitarios" },
  { value: "tabler:truck", label: "Frete", group: "Utilitarios" },
  { value: "tabler:package", label: "Encomenda", group: "Utilitarios" },
  { value: "tabler:package-export", label: "Entrega rapida", group: "Utilitarios" },
  { value: "tabler:message-chatbot", label: "Atendimento", group: "Utilitarios" },
  { value: "tabler:shield-check", label: "Confiavel", group: "Utilitarios" },
  { value: "tabler:map-pin", label: "Local", group: "Utilitarios" },
  { value: "tabler:stars", label: "Destaque", group: "Utilitarios" },
  { value: "tabler:clock-hour-4", label: "Plantao", group: "Utilitarios" },
  { value: "tabler:calendar-time", label: "Agendamento", group: "Utilitarios" },
  { value: "tabler:phone-call", label: "Telefone", group: "Utilitarios" },
  { value: "tabler:device-mobile", label: "Celular", group: "Utilitarios" },
  { value: "solar:buildings-bold-duotone", label: "Empresas", group: "Solar" },
  { value: "solar:home-2-bold-duotone", label: "Casa", group: "Solar" },
  { value: "solar:garage-bold-duotone", label: "Garagem", group: "Solar" },
  { value: "solar:shop-2-bold-duotone", label: "Loja", group: "Solar" },
  { value: "solar:shop-bold-duotone", label: "Comercio", group: "Solar" },
  { value: "solar:stethoscope-bold-duotone", label: "Clinica", group: "Solar" },
  { value: "solar:medal-ribbons-star-bold-duotone", label: "Especialista", group: "Solar" },
  { value: "solar:hand-heart-bold-duotone", label: "Cuidado", group: "Solar" },
  { value: "solar:shield-check-bold-duotone", label: "Seguranca", group: "Solar" },
  { value: "solar:delivery-bold-duotone", label: "Entrega", group: "Solar" },
  { value: "solar:smartphone-2-bold-duotone", label: "Online", group: "Solar" },
  { value: "solar:camera-bold-duotone", label: "Foto", group: "Solar" },
  { value: "solar:documents-bold-duotone", label: "Documentos", group: "Solar" },
  { value: "solar:users-group-rounded-bold-duotone", label: "Equipe", group: "Solar" },
  { value: "solar:user-check-bold-duotone", label: "Profissional", group: "Solar" },
  { value: "solar:cat-bold-duotone", label: "Pet", group: "Solar" },
  { value: "solar:palette-round-bold-duotone", label: "Design", group: "Solar" },
  { value: "solar:bill-list-bold-duotone", label: "Financeiro", group: "Solar" },
  { value: "solar:case-round-minimalistic-bold-duotone", label: "Negocios", group: "Solar" },
  { value: "solar:course-up-bold-duotone", label: "Aulas", group: "Solar" },
  { value: "ph:briefcase-duotone", label: "Profissional", group: "Phosphor" },
  { value: "ph:buildings-duotone", label: "Empresa", group: "Phosphor" },
  { value: "ph:storefront-duotone", label: "Comercio", group: "Phosphor" },
  { value: "ph:toilet-paper-duotone", label: "Diarista", group: "Phosphor" },
  { value: "ph:wrench-duotone", label: "Tecnico", group: "Phosphor" },
  { value: "ph:paint-brush-broad-duotone", label: "Pintura", group: "Phosphor" },
  { value: "ph:scissors-duotone", label: "Corte", group: "Phosphor" },
  { value: "ph:needle-duotone", label: "Costura", group: "Phosphor" },
  { value: "ph:car-duotone", label: "Auto", group: "Phosphor" },
  { value: "ph:truck-duotone", label: "Mudanca", group: "Phosphor" },
  { value: "ph:dog-duotone", label: "Pet", group: "Phosphor" },
  { value: "ph:first-aid-kit-duotone", label: "Saude", group: "Phosphor" },
  { value: "ph:heartbeat-duotone", label: "Bem estar", group: "Phosphor" },
  { value: "ph:book-open-duotone", label: "Ensino", group: "Phosphor" },
  { value: "ph:camera-duotone", label: "Foto", group: "Phosphor" },
  { value: "ph:hammer-duotone", label: "Obra", group: "Phosphor" },
  { value: "ph:hard-hat-duotone", label: "Construcao", group: "Phosphor" },
  { value: "ph:currency-circle-dollar-duotone", label: "Financas", group: "Phosphor" },
  { value: "ph:map-pin-line-duotone", label: "Local", group: "Phosphor" },
  { value: "ph:star-duotone", label: "Destaque", group: "Phosphor" },
  { value: "material-symbols:local-shipping-outline-rounded", label: "Frete", group: "Material" },
  { value: "material-symbols:local-laundry-service-outline-rounded", label: "Lavanderia", group: "Material" },
  { value: "material-symbols:construction-outline-rounded", label: "Construcao", group: "Material" },
  { value: "material-symbols:electrical-services-outline-rounded", label: "Eletrica", group: "Material" },
  { value: "material-symbols:plumbing-outline-rounded", label: "Hidraulica", group: "Material" },
  { value: "material-symbols:cleaning-services-outline-rounded", label: "Limpeza", group: "Material" },
  { value: "material-symbols:support-agent-rounded", label: "Suporte", group: "Material" },
  { value: "material-symbols:diversity-3-rounded", label: "Equipe", group: "Material" },
  { value: "material-symbols:event-available-rounded", label: "Agenda", group: "Material" },
  { value: "material-symbols:inventory-2-outline-rounded", label: "Estoque", group: "Material" },
  { value: "material-symbols:workspace-premium-outline-rounded", label: "Premium", group: "Material" },
  { value: "material-symbols:location-city-rounded", label: "Cidade", group: "Material" },
  { value: "material-symbols:emoji-people-outline-rounded", label: "Atendimento", group: "Material" },
  { value: "material-symbols:volunteer-activism-outline-rounded", label: "Assistencia", group: "Material" },
  { value: "material-symbols:health-and-safety-outline-rounded", label: "Saude", group: "Material" },
  { value: "material-symbols:pets-outline-rounded", label: "Pets", group: "Material" },
  { value: "material-symbols:auto-fix-high-rounded", label: "Manutencao", group: "Material" },
  { value: "material-symbols:content-cut-rounded", label: "Estilo", group: "Material" },
  { value: "material-symbols:sell-outline-rounded", label: "Oferta", group: "Material" },
  { value: "material-symbols:qr-code-scanner-rounded", label: "Scanner", group: "Material" },
];
